aoi_file: path/to/your/boundary.geojson
auth_method: service_account
chunk_size: 1000
confidence_threshold: 0.75
create_index: true
dataset_version: v3
export_format: geojson
include_area: true
include_confidence: true
include_plus_codes: true
max_area_m2: 100000.0
max_features: null
min_area_m2: 10.0
output_dir: path/to/output/directory
overwrite_existing: false
retry_attempts: 3
service_account_key: path/to/service-account-key.json
timeout_minutes: 30
